//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LargeEmployer.Model
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ESFA.DC.Data.LargeEmployer.Model.Interface;

    public partial class LargeEmployer : DbContext, ILargeEmployers
    {
        public LargeEmployer()
            : base("name=LargeEmployer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public DbSet<LargeEmployers> LargeEmployers { get; set; }
        public DbSet<SourceFile> SourceFiles { get; set; }
        public DbSet<VersionInfo> VersionInfoes { get; set; }
    }
}
