//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LargeEmployer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ESFA.DC.Data.LargeEmployer.Model.Interface;

    public partial class LargeEmployer : DbContext, ILargeEmployer
    {
        public LargeEmployer()
            : base("name=LargeEmployer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LEMP_Employers> LEMP_Employers { get; set; }
        public virtual DbSet<LEMP_SourceFile> LEMP_SourceFile { get; set; }
        public virtual DbSet<LEMP_VersionInfo> LEMP_VersionInfo { get; set; }
    }
}
